### ISSUE TITLE
第一课的疑问，关于合约内方法的调用者和 gas 消费的关系

### ISSUE THREAD

**Issue by laberat** [linjie-1/guigulive-operation#56]
根据第一课内容，一个 contract 可以部署在一个 block 上，一般来说还需要提供一些 gas limit 给 block 的维护者（矿工）。
那么，

- contract的部署和其方法的调用是什么关系？
- contract是每个合法身份的 Address 都可以发起调用吗？发起调用的 Address 需要支付 gas 吗？
- 课程里如果 getPaid 没做检查的话，那么 frank.transfer 这个操作是 frank 支付 gas，还是调用者支付 gas？

**Comment by lsdlinshunda** [comment]
终于有学员在issue里提问题了，简单回答下：

1. 合约部署到链上后会有一个合约地址，通过合约地址可以调用其中的方法，调用的形式相当于向合约地址发起一个transaction
2. 每个合法的address都可以发起调用，普通的用户地址可以调用合约，同时合约之间也是可以相互调用的。gas是由一开始发起transaction的地址进行支付
3. frank.transfer这个操作是调用者支付gas

**Comment by minzhi3** [comment]
关于第二点是不是这么理解，比如我->合约A->合约B->合约C这样调用的话，所有的gas都是我付的？ @lsdlinshunda

**Comment by lsdlinshunda** [comment]
@minzhi3 
是的，"合约A->合约B->合约C"这个过程中产生的计算步骤也都是算在你头上的。
更详细的一些介绍可以阅读这篇文章：
> http://ethfans.org/posts/797
如果交易所产生的所有计算步骤（包含原始消息和可能被触发的所有其他消息）所需要的气的总量小于等于交易中指定的气的上限，交易会被处理。如果实际消耗的气的总量超过交易中气的上限，所有的变动都会被回复原样，除了交易仍然有效，且费用仍可以被矿工收取。

**Comment by laberat** [comment]
@lsdlinshunda 非常感谢。可以关闭 issue 了。不知道关闭是我自己操作还是由助教操作。

**Comment by lsdlinshunda** [comment]
@laberat 以后如果问题解答了，就由你们提issue的人自己关闭吧
