### ISSUE TITLE
关于AddFund，如何实现只添加新的一些fund

### ISSUE THREAD

**Issue by topmorphs** [linjie-1/guigulive-operation#65]
想实现以下功能，但不能通过编译。
function addFund(uint amount) returns (uint) {
        this.balance=this.balance+amount;
        return this.balance;
    } 
如何实现呢？

**Comment by lsdlinshunda** [comment]
合约的balance不能通过这种方式直接改，是自动计算的。
在调用带payable的函数时附带上value给合约打钱，合约的balance会自动变化。
```
    function addFund() payable returns (uint){
        return this.balance;
    }
```
![image](https://raw.githubusercontent.com/lsdlinshunda/MarkdownPhotos/master/Photos/guigulive/1.9_value%E7%A4%BA%E6%84%8F%E5%9B%BE.png)
